
cinnamon = Ingredient.create!(name: 'cinnamon', category: 8)
cumin = Ingredient.create!(name: 'cumin', category: 8)
black = Ingredient.create!(name: 'black pepper', category: 8)
cloves = Ingredient.create!(name: 'cloves', category: 8)
cardamom = Ingredient.create!(name: 'cardamom', category: 8)
tarragon = Ingredient.create!(name: 'tarragon', category: 8)
honey = Ingredient.create!(name: 'honey', category: 8)
agave = Ingredient.create!(name: 'agave', category: 8)
ground = Ingredient.create!(name: 'ground cardamom', category: 8)
turmeric = Ingredient.create!(name: 'turmeric', category: 8)
rosemary = Ingredient.create!(name: 'rosemary', category: 8)
allspice = Ingredient.create!(name: 'allspice', category: 8)
d_sage = Ingredient.create!(name: 'dried sage', category: 8)
d_celery = Ingredient.create!(name: 'dried celery seed', category: 8)
basil = Ingredient.create!(name: 'basil', category: 8)
himal_salt = Ingredient.create!(name: 'Himalayan salt', category: 8)
s_salt = Ingredient.create!(name: 'sea salt', category: 8)
brown_s = Ingredient.create!(name: 'brown sugar', category: 8)
nutmeg = Ingredient.create!(name: 'nutmeg', category: 8)
vanilla = Ingredient.create!(name: 'vanilla extract', category: 8)
italian_h = Ingredient.create!(name: 'italian herbs', category: 8)
g_coriander = Ingredient.create!(name: 'ground coriander', category: 8)
g_ginger = Ingredient.create!(name: 'ground ginger', category: 8)
cayenne = Ingredient.create!(name: 'cayenne pepper', category: 8)
onion_p = Ingredient.create!(name: 'onion powder', category: 8)
coriander = Ingredient.create!(name: 'coriander', category: 8)
oregano = Ingredient.create!(name: 'oregano', category: 8)
mint = Ingredient.create!(name: 'mint', category: 8)
parsley = Ingredient.create!(name: 'parsley', category: 8)
bay = Ingredient.create!(name: 'bay leaf', category: 8)
chili_p = Ingredient.create!(name: 'red chili pepper', category: 8)
sriracha = Ingredient.create!(name: 'sriracha', category: 8)
chipotle_p = Ingredient.create!(name: 'smoked chipotle powder', category: 8)
dill = Ingredient.create!(name: 'dill', category: 8)

water = Ingredient.create!(name: 'water', category: 9)
carrot_e = Ingredient.create!(name: 'carrot essence', category: 9)
evoo = Ingredient.create!(name: 'extra virgin olive oil', category: 9)
b_vinegar = Ingredient.create!(name: 'balsamic vinegar', category: 9)

butter = Ingredient.create!(name: 'butter', category: 0)
manchego = Ingredient.create!(name: 'manchego', category: 0)
goat_c = Ingredient.create!(name: 'goat cheese', category: 0)
coco_milk = Ingredient.create!(name: 'coconut milk', category: 0)
rice_milk = Ingredient.create!(name: 'rice milk', category: 0)
c_milk = Ingredient.create!(name: "cow's milk", category: 0)

carrot = Ingredient.create!(name: 'carrot', category: 2)
r_onion = Ingredient.create!(name: 'red onion', category: 2)
w_onion = Ingredient.create!(name: 'white onion', category: 2)
zucchini = Ingredient.create!(name: 'zucchini', category: 2)
garlic = Ingredient.create!(name: 'garlic', category: 2)
ginger = Ingredient.create!(name: 'ginger', category: 2)
broccoli = Ingredient.create!(name: 'broccoli', category: 2)
avocado = Ingredient.create!(name: 'avocado', category: 2)
escarole = Ingredient.create!(name: 'escarole', category: 2)
kale = Ingredient.create!(name: 'kale', category: 2)
scallions = Ingredient.create!(name: 'scallions', category: 2)
leeks = Ingredient.create!(name: 'leeks', category: 2)
y_squash = Ingredient.create!(name: 'yellow squash', category: 2)
beet = Ingredient.create!(name: 'beet', category: 2)
y_onion = Ingredient.create!(name: 'yellow onion', category: 2)
shiitake = Ingredient.create!(name: 'shiitake mushrooms', category: 2)
frisee = Ingredient.create!(name: 'frisee', category: 2)
radicchio = Ingredient.create!(name: 'radicchio', category: 2)
potatoes = Ingredient.create!(name: 'potatoes', category: 2)
brussels = Ingredient.create!(name: 'brussels sprouts', category: 2)
edamame = Ingredient.create!(name: 'edamame', category: 2)
asparagus = Ingredient.create!(name: 'asparagus', category: 2)
spinach = Ingredient.create!(name: 'spinach', category: 2)

lime = Ingredient.create!(name: 'lime', category: 1)
lemon = Ingredient.create!(name: 'lemon', category: 1)
pear = Ingredient.create!(name: 'pear', category: 1)
blueberries = Ingredient.create!(name: 'blueberries', category: 1)
apple = Ingredient.create!(name: 'apple', category: 1)
mango = Ingredient.create!(name: 'mango', category: 1)
banana = Ingredient.create!(name: 'banana', category: 1)
raisins = Ingredient.create!(name: 'raisins', category: 1)
apricot = Ingredient.create!(name: 'apricot jam', category: 1)
cranberries = Ingredient.create!(name: 'cranberries', category: 1)
d_cranb = Ingredient.create!(name: 'dried cranberries', category: 1)
watermelon = Ingredient.create!(name: 'watermelon', category: 1)
tomatoes = Ingredient.create!(name: 'tomatoes', category: 1)
oranges = Ingredient.create!(name: 'oranges', category: 1)

thighs = Ingredient.create!(name: 'chicken thighs', category: 6)
c_stock = Ingredient.create!(name: 'chicken stock', category: 6)
chicken = Ingredient.create!(name: 'whole chicken', category: 6)
c_breast = Ingredient.create!(name: 'chicken breast', category: 6)
eggs = Ingredient.create!(name: 'eggs', category: 6)
deli = Ingredient.create!(name: 'deli meats', category: 6)
steak = Ingredient.create!(name: 'steak', category: 6)
lamb = Ingredient.create!(name: 'lamb', category: 6)
ground = Ingredient.create!(name: 'ground lamb', category: 6)

wild = Ingredient.create!(name: 'wild white fish', category: 7)
halibut = Ingredient.create!(name: 'halibut', category: 7)
flounder = Ingredient.create!(name: 'flounder', category: 7)
tuna = Ingredient.create!(name: 'tuna', category: 7)
salmon = Ingredient.create!(name: 'salmon', category: 7)
scallops = Ingredient.create!(name: 'scallops', category: 7)

lentils = Ingredient.create!(name: 'lentils', category: 3)
pinto = Ingredient.create!(name: 'pinto beans', category: 3)
black = Ingredient.create!(name: 'black beans', category: 3)

chia = Ingredient.create!(name: 'chia seeds', category: 4)
flaxseeds = Ingredient.create!(name: 'flaxseeds', category: 4)
almonds = Ingredient.create!(name: 'almonds', category: 4)
sunflower = Ingredient.create!(name: 'sunflower seeds', category: 4)
pumpkin = Ingredient.create!(name: 'pumpkin seeds', category: 4)
peanuts = Ingredient.create!(name: 'peanuts', category: 4)
almond = Ingredient.create!(name: 'almond slivers', category: 4)
almond_b = Ingredient.create!(name: 'almond butter', category: 4)
peanut = Ingredient.create!(name: 'peanut butter', category: 4)

almond_f = Ingredient.create!(name: 'almond flour', category: 5)
spelt = Ingredient.create!(name: 'spelt flakes', category: 5)
basmati = Ingredient.create!(name: 'basmati rice', category: 5)
jasmine = Ingredient.create!(name: 'jasmine rice', category: 5)
white = Ingredient.create!(name: 'white bread', category: 5)
pasta = Ingredient.create!(name: 'pasta', category: 5)
bagel = Ingredient.create!(name: 'bagel', category: 5)
oatmeal = Ingredient.create!(name: 'oatmeal', category: 5)

flax_granola = Recipe.create!(title: 'Flax Granola', instructions: "Preheat oven to 275F degrees. Combine water and flaxseeds in a medium bowl and mix well. Let sit for 30 minutes and mix again. Add agave, cinnamon, cardamom, vanilla extract and nutmeg to flaxseeds and mix thoroughly.\nSpread granola in a thin layer on a baking sheet and bake for 50 minutes. Reduce oven temperature to 225F degrees. Cut sheet of granola into clusters, flip and bake an additional 30-40 minutes, until thoroughly dry. Add raisins and store in airtight container. Consume within 2 weeks.", servings: 3 , category: 0)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: water.id, amount: 1, unit: 2)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: flaxseeds.id, amount: 2, unit: 2)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: agave.id, amount: 1, unit: 1)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: cinnamon.id, amount: 2, unit: 0)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: cardamom.id, amount: 1, unit: 0)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: vanilla.id, amount: 1, unit: 0)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: nutmeg.id, amount: 0.5, unit: 0)
Amount.create!(recipe_id: flax_granola.id, ingredient_id: raisins.id, amount: 0.5, unit: 2)

c_g_soup = Recipe.create!(title: 'Carrot Ginger Soup', instructions: "Combine Cinnamon, cumin, black pepper, cloves, cardamom, turmeric, and allspice in a dry skillet over medium-low heat and cook, stirring constantly, for 30 seconds. IN a large soup pot, combine water, carrots, onions, zucchini, garlic, ginger, and olive oil; add toasted spices. Bring water to a boil and then let simmer for 45 minutes, until carrots are soft.\nReserve 2 to 4 quarts of the broth for future soup stocks. Transfer remaining soup to a blender in batches and puree.\nNote: You can add one 14oz can of full-fat unsweetened coconut milk and 5 to 6 Vietnamese chili peppers while cooking for a creamier, spicier soup.", servings: 13, category: 1)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: cinnamon.id, amount: 1, unit: 1)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: cumin.id, amount: 1, unit: 1)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: black.id, amount: 1, unit: 1)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: cloves.id, amount: 1, unit: 0)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: cardamom.id, amount: 1, unit: 0)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: turmeric.id, amount: 0.5, unit: 0)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: allspice.id, amount: 0.5, unit: 0)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: water.id, amount: 7, unit: 4)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: carrot.id, amount: 5, unit: 6)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: r_onion.id, amount: 2, unit: 8)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: zucchini.id, amount: 3, unit: 8)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: garlic.id, amount: 8, unit: 11)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: ginger.id, amount: 5, unit: 12)
Amount.create!(recipe_id: c_g_soup.id, ingredient_id: evoo.id, amount: 2, unit: 1)

beet_c_salad = Recipe.create!(title: 'Beet Carrot Salad', instructions: "Grate carrots and beet. Stores well in Tupperware for a week. Please dress with lemon and evoo during the cleanse for best liver gall bladder health", servings: 4, category: 2)
Amount.create!(recipe_id: beet_c_salad.id, ingredient_id: carrot.id, amount: 4.5, unit: 10)
Amount.create!(recipe_id: beet_c_salad.id, ingredient_id: beet.id, amount: 1, unit: 9)

spicy_coco = Recipe.create!(title: 'Spicy Coco Sauce', instructions: "In a large saucepan, heat olive oil over medium heat. Add onion and garlic and sauté until they start to turn brown. Add ginger, cumin, cinnamon, pepper, coriander, nutmeg, cardamom, and allspice and sauté for 1 minute at low heat, until spices start to smell fragrant. Add coconut milk, Sriracha, brown sugar, and lemongrass, if desired, stirring for 30 seconds. Reduce heat and simmer, stirring for every 5 minutes, for 15 to 20 minutes, so flavors can fully integrate. Remove lemongrass. Serve immediately or let cool and then freeze.", servings: 5, category: 4)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: evoo.id, amount: 3, unit: 2)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: w_onion.id, amount: 1, unit: 8)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: garlic.id, amount: 4, unit: 11)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: ginger.id, amount: 2, unit: 12, comment: 'roughly 1 tbsp')
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: cumin.id, amount: 2, unit: 0)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: cinnamon.id, amount: 1, unit: 0)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: black.id, amount: 1, unit: 0)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: coriander.id, amount: 1, unit: 0)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: allspice.id, amount: 0.5, unit: 0)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: coco_milk.id, amount: 1, unit: 7, comment: '14 oz')
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: sriracha.id, amount: 4, unit: 2)
Amount.create!(recipe_id: spicy_coco.id, ingredient_id: brown_s.id, amount: 1, unit: 2)

broccoli = Recipe.create!(title: 'Cream of Broccoli Soup', instructions: "Sautee onion and spices in 3 tbsp of butter. Add in all ingredients and cook until vegetables are tender, approximately 25-30 minutes.\nAdd in avocado, blend and serve! For a less creamy soup, add more water.", servings: 7, category: 1)
Amount.create!(recipe_id: broccoli.id, ingredient_id: butter.id, amount: 3, unit: 1)
Amount.create!(recipe_id: broccoli.id, ingredient_id: w_onion.id, amount: 1, unit: 8)
Amount.create!(recipe_id: broccoli.id, ingredient_id: d_sage.id, amount: 1, unit: 1)
Amount.create!(recipe_id: broccoli.id, ingredient_id: cumin.id, amount: 1, unit: 0)
Amount.create!(recipe_id: broccoli.id, ingredient_id: d_celery.id, amount: 0.5, unit: 0)
Amount.create!(recipe_id: broccoli.id, ingredient_id: carrot_e.id, amount: 2, unit: 2)
Amount.create!(recipe_id: broccoli.id, ingredient_id: water.id, amount: 2, unit: 2)
Amount.create!(recipe_id: broccoli.id, ingredient_id: coco_milk.id, amount: 1, unit: 7)
Amount.create!(recipe_id: broccoli.id, ingredient_id: broccoli.id, amount: 8, unit: 2, comment: 'about 4 heads of broccoli')
Amount.create!(recipe_id: broccoli.id, ingredient_id: zucchini.id, amount: 4, unit: 2, comment: 'about 2 medium zucchini')
Amount.create!(recipe_id: broccoli.id, ingredient_id: avocado.id, amount: 1, unit: 9)
Amount.create!(recipe_id: broccoli.id, ingredient_id: sriracha.id, amount: 1, unit: 1, optional: true)
Amount.create!(recipe_id: broccoli.id, ingredient_id: black.id, comment: 'To taste')

smoothie = Recipe.create!(title: 'The Plan Smoothie', instructions: "Fill Blender with enough Rice Dream or Silk Coconut Milk  to fill to 16 or 20 oz. Blend. Ice is not recommended if you have thyroid dysfunction.", servings: 1, category: 0)
Amount.create!(recipe_id: smoothie.id, ingredient_id: pear.id, amount: 1,  unit: 13, comment: "ripe")
Amount.create!(recipe_id: smoothie.id, ingredient_id: blueberries.id, amount: 0.5, unit: 2)
Amount.create!(recipe_id: smoothie.id, ingredient_id: avocado.id, amount: 0.25, unit: 13)
Amount.create!(recipe_id: smoothie.id, ingredient_id: chia.id, amount: 0.25, unit: 2)
Amount.create!(recipe_id: smoothie.id, ingredient_id: rice_milk.id, amount: 2, unit: 2, comment: "or Silk Coconut Milk")
Amount.create!(recipe_id: smoothie.id, ingredient_id: honey.id, amount: 1, unit: 0, optional: true)
Amount.create!(recipe_id: smoothie.id, ingredient_id: agave.id, amount: 1, unit: 0, optional: true)
Amount.create!(recipe_id: smoothie.id, ingredient_id: vanilla.id, optional: true, comment: 'To taste')
Amount.create!(recipe_id: smoothie.id, ingredient_id: cinnamon.id, optional: true, comment: 'To taste')
